language: node_js

sudo: true

env:
  - CXX=g++-4.8 NODE_ENV=testing DB_NAME_TEST=db_mmexpress-js_test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE \"$DB_NAME_TEST\";" -U postgres
  - npx sequelize db:migrate
